#!/bin/bash 

  echo "Starting config: " 
  whoami 
  date 
  sleep 1

  echo cape-universaln > /sys/devices/bone_capemgr.9/slots

  date >> /home/debian/starting.log
  config-pin p9.14 pwm
  config-pin p9.16 pwm

  sleep 1
  echo 3 > /sys/class/pwm/export
  date >> /home/debian/starting.log
  echo 4 > /sys/class/pwm/export

  sleep 1
  echo 20000000 > /sys/class/pwm/pwm3/period_ns
  date >> /home/debian/starting.log
  echo 20000000 > /sys/class/pwm/pwm4/period_ns

  echo 1500000 > /sys/class/pwm/pwm4/duty_ns
  echo 1500000 > /sys/class/pwm/pwm3/duty_ns


  sleep 1 
  date >> /home/debian/starting.log
  echo 1 > /sys/class/pwm/pwm3/run
  echo 1 > /sys/class/pwm/pwm4/run

